### ISSUE TITLE
No 'version' key in the manifest file integration will no longer be loaded in new Version of homeassistant

### ISSUE THREAD

**Issue by AlexQuaken** [CorneliousJD/flux_led#10]
ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'flux_led'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'flux_led'

**Comment by CorneliousJD** [comment]
This has already been fixed.  
See #7 
https://github.com/CorneliousJD/Flux_LED/issues/7

Just download latest copy and replace.
