### ISSUE TITLE
Suddenly dosent work

### ISSUE THREAD

**Issue by Curros** [CorneliousJD/flux_led#12]
Hello all, really thanks for your work, a couple of days ago (I not sure If I did an update) the controller stop working with HACS.

The same issue if I put your changes, or If I delete everything.

Using MagicLight everything works as expected, but as soon I start HASS with or without the Flux-led folder, the lights stop working.

I came back to see if you have updated something or whatever and the last time I put the files manually, this time I try HACS but its not picking the URL.

## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Madrid

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4464
Installed Version | 1.13.2
Stage | running
Available Repositories | 843
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 57.8 GB
disk_used | 7.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.3.0), File editor (5.3.3), Node-RED (8.2.1), Samba share (9.5.1), Terminal & SSH (9.1.3), ArgonOne Active Cooling (23.0), HassOS I2C Configurator (0.13)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 3
mode | storage

</details>

**Comment by CorneliousJD** [comment]
Not sure if your magiclight device itself did a firmware update or something - but this repo was really just to document code that worked for *me* and if it helps others, then awesome.

Unfortuantely I do not have the time or knowledge to help others troubleshoot their issues.
I will leave this open though incase others see it and drop in with suggestions.
