### ISSUE TITLE
No version key

### ISSUE THREAD

**Issue by fireport** [CorneliousJD/flux_led#7]
Hello CorneliousJD I've appreciated a lot your fix but today I see this message in home assistant log:
`No 'version' key in the manifest file for custom integration 'flux_led'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'flux_led'` 
Can you fix this?
Thank you

**Comment by CorneliousJD** [comment]
Fixed! Just download/replace the manifest.json file and you should be all good, thanks for reporting this :)
